//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateSystem.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimatePublication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstimatePublication()
        {
            this.EstimateEditions = new HashSet<EstimateEdition>();
            this.EstimateScheduleds = new HashSet<EstimateScheduled>();
        }
    
        public int EST_PUBID { get; set; }
        public string EST_Publication { get; set; }
        public int EST_ID { get; set; }
        public string Pub_Language { get; set; }
        public int Total_Edition { get; set; }
        public decimal Rate { get; set; }
        public int Total_Insertion { get; set; }
        public decimal Total_Cost { get; set; }
        public decimal Agency_Discount { get; set; }
        public decimal Total_NetCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateEdition> EstimateEditions { get; set; }
        public virtual EstimateHeader EstimateHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateScheduled> EstimateScheduleds { get; set; }
    }
}
