//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateSystem.BL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstimateDBEntities : DbContext
    {
        public EstimateDBEntities()
            : base("name=EstimateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CaptionMaster> CaptionMasters { get; set; }
        public virtual DbSet<ClientMaster> ClientMasters { get; set; }
        public virtual DbSet<EstimatePublication> EstimatePublications { get; set; }
        public virtual DbSet<BrandMaster> BrandMasters { get; set; }
        public virtual DbSet<EstimateEdition> EstimateEditions { get; set; }
        public virtual DbSet<EstimateHeader> EstimateHeaders { get; set; }
        public virtual DbSet<EstimateScheduled> EstimateScheduleds { get; set; }
    }
}
