//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateSystem.BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstimateHeader()
        {
            this.EstimateEditions = new HashSet<EstimateEdition>();
            this.EstimatePublications = new HashSet<EstimatePublication>();
            this.EstimateScheduleds = new HashSet<EstimateScheduled>();
        }
    
        public int EST_ID { get; set; }
        public string EST_NO { get; set; }
        public System.DateTime EST_Date { get; set; }
        public string Campaign { get; set; }
        public string Agency { get; set; }
        public string PO_NO { get; set; }
        public System.DateTime PO_Date { get; set; }
        public int ClientID { get; set; }
        public int BrandID { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public System.DateTime PeriodTo { get; set; }
        public decimal SAC_PER { get; set; }
        public decimal AAC_PER { get; set; }
        public decimal Gross_Cost { get; set; }
        public decimal Net_Cost { get; set; }
        public int Status { get; set; }
    
        public virtual BrandMaster BrandMaster { get; set; }
        public virtual ClientMaster ClientMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateEdition> EstimateEditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimatePublication> EstimatePublications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimateScheduled> EstimateScheduleds { get; set; }
    }
}
